export const CLIENT_ENV = {
  ADSENSE_PUBLISHER_ID: process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID,

  ADSENSE_LEFT_SLOT_ID: process.env.NEXT_PUBLIC_ADSENSE_LEFT_SLOT_ID,
  ADSENSE_RIGHT_SLOT_ID: process.env.NEXT_PUBLIC_ADSENSE_RIGHT_SLOT_ID,
  ADSENSE_TOP_SLOT_ID: process.env.NEXT_PUBLIC_ADSENSE_TOP_SLOT_ID,
  ADSENSE_BOTTOM_SLOT_ID: process.env.NEXT_PUBLIC_ADSENSE_BOTTOM_SLOT_ID,
};

if (!CLIENT_ENV.ADSENSE_PUBLISHER_ID) {
  console.warn('⚠️ Missing ADSENSE_PUBLISHER_ID');
}

if (!CLIENT_ENV.ADSENSE_LEFT_SLOT_ID) {
  console.warn('⚠️ Missing ADSENSE_LEFT_SLOT_ID');
}

if (!CLIENT_ENV.ADSENSE_RIGHT_SLOT_ID) {
  console.warn('⚠️ Missing ADSENSE_RIGHT_SLOT_ID');
}

if (!CLIENT_ENV.ADSENSE_TOP_SLOT_ID) {
  console.warn('⚠️ Missing ADSENSE_TOP_SLOT_ID');
}

if (!CLIENT_ENV.ADSENSE_BOTTOM_SLOT_ID) {
  console.warn('⚠️ Missing ADSENSE_BOTTOM_SLOT_ID');
}
